runtime: python37
entrypoint: gunicorn -b :$PORT wishlist.wsgi

handlers:
- url: /static
  static_dir: www/static/

- url:/.*
  script: auto

env_variables:
  TRAVELER_PW: PHP4me2

beta_settings:
  cloud_sql_instances: travel-wish-list-274319:us-central1:travelwishlist-db
